### PR TITLE
Biomes contined

### PR DESCRIPTION
**Pull request by ZachNich**
## Changes
  * biomes FINISHED
  * conditions added for adding animals and plants to biomes
  * check that shit OUT, it may not work

### CODE REVIEW

**Comment by iamkaleb** [comment]
A pristine example of what Python should be. 500 and a half stars. This will serve as a milestone of human achievement for a generation of programmers. 👍 👍

**Comment by eli-roberts** [comment]
👍 🔥 😲 💯

**Comment by johnbain881** [comment]
👍

**Comment by ZachNich** [comment]
Thanks guys. I think we will look back on this day as a turning point in our lives, not only as developers, but also as human beings.

**Pull request merged**
